# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Hitchin Chamber Orchestra
email: hitchinchamberorch@gmail.com
description: Hitchin Chamber Orchestra (HCO) is a friendly string orchestra based in Hitchin aiming to present high standard concerts in the town’s lovely venues.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://hitchinchamberorchestra.org" # the base hostname & protocol for your site
twitter_username: tzkuei

# Build settings
markdown: kramdown
